### ISSUE TITLE
npm listed as dependency

### ISSUE THREAD

**Issue by huan086** [ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator#23]
I don't see anywhere in the code that has a direct dependency on npm, but it is listed as a dependency in package.json.

It causes all npm commands to be using this local version instead of the global one. This is a problem because the local version is too old for the version of node (v12) installed in my system.

Is it possible to remove npm as a dependency in package.json?

**Comment by ffMathy** [comment]
That's a good idea! PRs welcome. I don't recall that that dependency is there on purpose.
