### ISSUE TITLE
Merge Options in FileEmitter is broken.

### ISSUE THREAD

**Issue by Logical-sh** [ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator#6]
The merge options in the file emitter merges the class options (and likely many more) with themselves instead of the intended target. This results in the property options being lost.
It looks like this effects ALOT of the option merges.

    if(options.propertyEmitOptions) {
        if(options.classEmitOptions) {
            options.classEmitOptions.propertyEmitOptions = 
    	        this.optionsHelper.mergeOptions(
    	            options.classEmitOptions,
    		    options.classEmitOptions.propertyEmitOptions);
        }
        ....
    }

**Comment by ffMathy** [comment]
This is currently being fixed in the branch here: https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator/tree/typescript-compiler-service

It is a quite big upgrade to the emitter, and also changes how inheritance is done.

**Comment by ffMathy** [comment]
I continued working on this. I hope to get it fixed within the new year.

**Comment by jannesiera** [comment]
What is the status on this?

**Comment by ffMathy** [comment]
I expect to be done some time next week. See the other branch for more details.

**Comment by ffMathy** [comment]
Merging now works in the feature branch, but tests are failing. I know what's causing it though but don't have time to work on it until Monday.

**Comment by ffMathy** [comment]
I have been ill now for a while and have hence had a bit of time to work on it. Amount of failing tests as of the day before yesterday is now down to around 15 instead of 29.

This project is now also my top priority.

**Comment by ffMathy** [comment]
Here is the branch with progress if you want to help out.

**Comment by ffMathy** [comment]
https://github.com/ffMathy/FluffySpoon.JavaScript.CSharpToTypeScriptGenerator/tree/typescript-compiler-service?files=1

**Comment by ffMathy** [comment]
One failing test remaining.

**Comment by jannesiera** [comment]
@ffMathy thanks for the great work. I don't have time to help out now, but I will test my use case the coming week.

**Comment by ffMathy** [comment]
If I make it. The last test requires some refactoring, but I am getting there.

When this issue is resolved I can continue: https://github.com/Microsoft/TypeScript/issues/23042

**Comment by ffMathy** [comment]
It has now been merged. I will update the `README.md` file to reflect the changes, because the way defaults are set globally has now changed slightly.

**Comment by ffMathy** [comment]
I just upgraded the documentation heavily as well. Enjoy! The library is also now 100% based on the TypeScript compiler API under the hood, and allows working directly with TypeScript objects if you wish.

**Comment by ffMathy** [comment]
Oh, and the package has now been put on NPM as well. That was about time.
